title: Eduardo Vieira
tagline: Personal blog
description: >
  Eduardo Vieira's personal blog — write-ups on software engineering
  and other topics of my interest.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eduardovra.github.io"

# Author Settings
author: Eduardo Vieira
author-img: eduardo.jpg
about-author: Write-ups on topics of my interest.
social-github: eduardovra
social-linkedin: eduardo-vieira-50940617

# SEO (jekyll-seo-tag)
logo: /assets/img/eduardo.jpg
twitter:
  username: eduardovra
  card: summary
social:
  name: Eduardo Vieira
  links:
    - https://github.com/eduardovra
    - https://www.linkedin.com/in/eduardo-vieira-50940617

# Disqus
discus-identifier: eduardovra # add your discus identifier

# Tracker
analytics: G-ZQGY85X7XW

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock"]
